name: Test

on: [push]

jobs:
  test-coverage:
    name: Test coverage
    runs-on: [ubuntu-latest]
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run testing
    - run: go test -v -coverprofile=profile.cov ./...

    - name: Send coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: profile.cov
