name: CodeCov

on: [push]

jobs:
  cd:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -coverprofile=coverage.out -covermode=count ./...

      - name: Make Coverage Badge
        run: |
          set -x
          total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi

          mkdir -p $(dirname build/coverage/coverage.svg)
          echo "generating coverage badge in $(dirname build/coverage/coverage.svg)"
          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > build/coverage/coverage.svg

      - name: Deploy badge
        # Only once from master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/coverage
          keep_files: true
