name: Quality
on: [push]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.15'
    - name: Set up GOPATH
      run: |
        echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run Unit tests
      run: go test -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
