name: Test

on: [push]

jobs:
  test:
    name: Unit Test
    runs-on: [ubuntu-latest]
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
      
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Test`
      run: go test -v ./...

  test-coverage:
    name: Test coverage
    runs-on: [ubuntu-latest]
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
      
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

