name: Quality

on: [push]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Unit tests
      run: go test ./... -race -covermode atomic -coverprofile=profile.cov

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
