name: CodeCov

on:
  push:
    branches: [ master ]

jobs:
  cd:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -coverprofile=coverage.out -covermode=count ./...

      - name: Make Coverage Badge
        run: .github/workflows/coverage.sh build/coverage/coverage.svg

      - name: Deploy badge
        # Only once from master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/coverage
          keep_files: true
